version: '3.8'

services:
  blog:
    build: .
    container_name: lys-blog
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
